# Uncomment the next line to define a global platform for your project
# platform :ios, ’11.0’

target 'SmartBbq' do
 # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmartBbq
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'


  pod 'Charts'
  pod 'BlueCapKit', '~> 0.6'

end
